import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Coming soon | tententgc </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to tententgc.com
        </h1>

        <p className={styles.description}>
          We have new update{' '}
          <code className={styles.code}>all code. </code>
        </p>


      </main>

    </div>
  )
}
